clone_folder: c:\gopath\src\github.com\danstis\Plex-Sync

environment:
  GOPATH: c:\gopath
  CODACY_TOKEN:
    secure: yrLZn0Ij30M2DLejKY+7ulU3d86KrrOxl/+vaBXmFPCPotquPtTWyRWUE7yIhez3
  GITHUB_TOKEN:
    secure: Yl/4x5Z5ys7ZvWZayu3S2Sh6rj5GMF/IKtXeuYIlfjdojJJC5sp3S8s35Dnzdcca

install:
  - choco install gitversion.portable -pre -y
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - echo %GOPATH%
  - go version
  - go get -v -t -d .\...

before_build:
  - go get -u github.com/haya14busa/goverage
  - go get -u github.com/schrej/godacov
  - gitversion /l console /output buildserver
  - ps: (Get-Content .\plex\version.go) -replace '(?<=Version = ").*?(?=")', $env:GitVersion_SemVer | Set-Content -Path .\plex\version.go -Encoding UTF8
  - goverage -v .\...
  - go tool cover -func coverage.out
  - echo %APPVEYOR_REPO_COMMIT%
  - godacov -t %CODACY_TOKEN% -r ./coverage.out -c %APPVEYOR_REPO_COMMIT%

build_script:
  - go build -race
  - ps: dir -Recurse

after_build:
  - ps: mv ./config/config.toml.default ./config/config.toml
  - ps: mv ./tvshows.txt.default ./tvshows.txt
  - ps: Get-ChildItem -Directory -Include ".*","plex","Plex-Sync" -Recurse -Force | %{Remove-Item $_ -Force}
  - ps: Get-ChildItem -Include "coverage.out",".*","*.go","_template.html" -Recurse -Force | %{Remove-Item $_ -Force}
  - ps: dir -Recurse

artifacts:
  - path: .\
    name: Plex-Sync
    type: zip
