clone_folder: c:\gopath\src\github.com\danstis\Plex-Sync

environment:
  GOPATH: c:\gopath
  GO111MODULE: on
  CODACY_TOKEN:
    secure: yrLZn0Ij30M2DLejKY+7ulU3d86KrrOxl/+vaBXmFPCPotquPtTWyRWUE7yIhez3
  COVERALLS_TOKEN:
    secure: Bc2t/iVXULjddywzFj+F5RrWTlqVHVv4ikA+NV9LZMt69OQRaauWcMDhpjlZ5FN/

install:
  - choco install gitversion.portable -y
  - rm C:\Tools\GitVersion\GitVersion.exe
  - mkdir %GOPATH%\bin
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version

before_build:
  - gitversion /output buildserver
  - go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo
  - go get

build_script:
  - ps: goversioninfo -64 -product-version="$env:GitVersion_SemVer" -ver-major="$env:GitVersion_Major" -ver-minor="$env:GitVersion_Minor" -ver-patch="$env:GitVersion_Patch"
  - ps: go build -ldflags "-X github.com/danstis/Plex-Sync/plex.Version=$($env:GitVersion_SemVer)" github.com/danstis/Plex-Sync

before_test:
  - go get -u github.com/haya14busa/goverage
  - go get -u github.com/schrej/godacov

test_script:
  - go vet ./...
  - goverage -v .\plex\...
  - go tool cover -func coverage.out

after_test:
  - dir *.out
  - echo %APPVEYOR_REPO_COMMIT%
  - godacov -t %CODACY_TOKEN% -r .\coverage.out -c %APPVEYOR_REPO_COMMIT% || exit 0
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f coverage.out
  - ps: mkdir ".\package\config",".\package\logs"
  - ps: Copy-Item .\config\tvshows.txt.default .\package\config\tvshows.txt
  - ps: Copy-Item .\web .\package -Recurse -Force
  - ps: Get-ChildItem -Path .\* -Include "*.exe","*.md","LICENSE" -Force | Copy-Item -Destination .\package
  - ps: Get-ChildItem -Path .\package\ -Include "_template.html","*.go" -Recurse -Force | Remove-Item -Force
  - 7z a Plex-Sync.zip %APPVEYOR_BUILD_FOLDER%\package\*

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
  - path: Plex-Sync.zip
    name: Plex-Sync

deploy:
  release: v$(GitVersion_SemVer)
  description: "Please check the [Changelog](https://github.com/danstis/Plex-Sync/blob/master/CHANGELOG.md) for change details."
  provider: GitHub
  auth_token:
    secure: Yl/4x5Z5ys7ZvWZayu3S2Sh6rj5GMF/IKtXeuYIlfjdojJJC5sp3S8s35Dnzdcca # GitHub Token
  artifact: Plex-Sync
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true # deploy on tag push only
