codecov:
  notify:
    require_ci_to_pass: yes

comment: false

coverage:
  precision: 2
  round: down
  range: "40...80"

  notify:
    slack:
      default:
        url: secret:T/oW7REjv2VwFuB2gNnVEffubTtNY/hSm7xFPZsg922aCPhwg9ZypGwFgksJgRkMGlj3e1XUy57tYwIr5heQJFji23ofqCcZco0sSKNF5XqIDb4KpUdoCkWDS/9hkZrzGGL7gfqUrdJURkqA1+sZkflk256VCwsx2yigIqArd+U=
        threshold: 1%

  status:
    project: yes
    patch: yes
    changes: no

  ignore:
    - "templates"
    - "static"
    - "*_test.go"
    - "tests"
