language: go
matrix:
  include:
    - go: 1.6
    - go: 1.7
    - go: 1.8
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
