clone_folder: c:\gopath\src\github.com\danstis\Plex-Sync

environment:
  GOPATH: c:\gopath
  CODACY_TOKEN:
    secure: Yl/4x5Z5ys7ZvWZayu3S2Sh6rj5GMF/IKtXeuYIlfjdojJJC5sp3S8s35Dnzdcca

install:
  - choco install gitversion.portable -pre -y
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - echo %GOPATH%
  - go version
  - go get -v -t -d .\...

before_build:
  - ps: gitversion /l console /output buildserver
  - ps: (Get-Content .\plex\version.go) -replace '(?<=Version = ").*?(?=")', $env:GitVersion_SemVer | Set-Content -Path .\plex\version.go -Encoding UTF8

build_script:
  - ps: go build -race
  - ps: dir

test_script:
  - go get -u github.com/haya14busa/goverage
  - go test -v .\...
  - goverage -v .\...
  - go tool cover -func coverage.out

after_test:
  - echo %APPVEYOR_REPO_COMMIT%
  - go get -u github.com/schrej/godacov
  - godacov -t "%CODACY_TOKEN%" -r ./coverage.out -c "%APPVEYOR_REPO_COMMIT%"
